-- SEED DE EVENTOS 2026
DELETE FROM eventos_base WHERE data >= '2026-01-01' AND data <= '2026-12-31';

INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-01-01', 'Santa Maria, Mãe de Deus', 'Tempo do Natal', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-01-04', 'Epifania do Senhor', 'Tempo do Natal', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-01-11', 'Batismo do Senhor', 'Tempo do Natal', 2, FALSE, TRUE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-01-18', '2º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-01-25', '3º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-02-01', '4º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-02-08', '5º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-02-15', '6º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-02-18', 'Quarta-feira de Cinzas', 'Quaresma', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-02-22', '0º Domingo da Quaresma', 'Quaresma', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-03-01', '1º Domingo da Quaresma', 'Quaresma', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-03-08', '2º Domingo da Quaresma', 'Quaresma', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-03-15', '3º Domingo da Quaresma', 'Quaresma', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-03-22', '4º Domingo da Quaresma', 'Quaresma', 5, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-03-29', 'Domingo de Ramos', 'Semana Santa', 3, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-02', 'Quinta-feira Santa (Ceia do Senhor)', 'Tríduo Pascal', 2, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-03', 'Sexta-feira Santa (Paixão do Senhor)', 'Tríduo Pascal', 3, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-04', 'Sábado Santo (Vigília Pascal)', 'Tríduo Pascal', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-05', 'Domingo de Páscoa', 'Tempo Pascal', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-12', '2º Domingo da Páscoa', 'Tempo Pascal', 2, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-19', '3º Domingo da Páscoa', 'Tempo Pascal', 2, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-04-26', '4º Domingo da Páscoa', 'Tempo Pascal', 2, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-05-03', '5º Domingo da Páscoa', 'Tempo Pascal', 2, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-05-10', '6º Domingo da Páscoa', 'Tempo Pascal', 2, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-05-17', 'Ascensão do Senhor', 'Tempo Pascal', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-05-24', 'Pentecostes', 'Tempo Pascal', 3, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-05-31', 'Santíssima Trindade', 'Tempo Comum', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-06-04', 'Corpus Christi', 'Tempo Comum', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-06-07', '9º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-06-12', 'Sagrado Coração de Jesus', 'Tempo Comum', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-06-14', '10º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-06-21', '11º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-06-28', '12º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-07-05', '13º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-07-12', '14º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-07-19', '15º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-07-26', '16º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-08-02', '17º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-08-09', '18º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-08-16', '19º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-08-23', '20º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-08-30', '21º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-09-06', '22º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-09-13', '23º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-09-20', '24º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-09-27', '25º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-10-04', '26º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-10-11', '27º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-10-12', 'Nossa Senhora Aparecida', 'Tempo Comum', 1, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-10-18', '28º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-10-25', '29º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-11-01', '30º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-11-02', 'Comemoração de Todos os Fiéis Defuntos', 'Tempo Comum', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-11-08', '31º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-11-15', '32º Domingo do Tempo Comum', 'Tempo Comum', 1, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-11-22', 'Nosso Senhor Jesus Cristo, Rei do Universo', 'Tempo Comum', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-11-29', '1º Domingo do Advento', 'Advento', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-12-06', '2º Domingo do Advento', 'Advento', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-12-13', '3º Domingo do Advento', 'Advento', 5, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-12-20', '4º Domingo do Advento', 'Advento', 4, FALSE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-12-25', 'Natal do Senhor', 'Tempo do Natal', 2, TRUE, FALSE);
INSERT INTO eventos_base (data, titulo, tempo_liturgico, cor_id, is_solenidade, is_festa) VALUES ('2026-12-27', '5º Domingo do Advento', 'Advento', 4, FALSE, FALSE);
